services:
  wordpress:
    container_name: openmynetwork--deve
    image: wordpress:latest
    ports:
      - "8888:80"
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST} 
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - "./wordpress:/var/www/html"
      - "./php.ini:/usr/local/etc/php/conf.d/php.ini"