services:
  wordpress:
    image: wordpress:6.6.2 
    container_name: omnapp-wordpress
    ports:
      - "3000:80"  
    volumes:
      - ./wordpress:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${LOCAL_HOST}
      WORDPRESS_DB_USER: ${LOCAL_DB_USER}
      WORDPRESS_DB_PASSWORD: ''
      WORDPRESS_DB_NAME: ${LOCAL_DB_NAME}
    networks:
      - wp_network

  nginx:
    image: nginx:alpine
    container_name: omnapp-nginx
    ports:
      - "3000:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - wp_network

  mysql:
    image: mysql:8.0
    container_name: omnapp-db
    environment:
      MYSQL_ROOT_PASSWORD: mjeRyvpqewm
      MYSQL_DATABASE: omn_migration_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: mjeRyvpqewm
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wp_network

volumes:
  mysql-data:

networks:
  wp_network:
