services:
  wordpress:
    image: wordpress:latest
    container_name: omn_wordpress
    ports:
      - "3000:80" 
    volumes:
      - ./wordpress:/var/www/html    # Mount local WordPress files
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes  # Mount local themes
      - ./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins  # Mount local plugins
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: omn_user
      WORDPRESS_DB_PASSWORD: 2Lc5/aEa*X,2
      WORDPRESS_DB_NAME: omn_production_db
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: omn_db
    environment:
      MYSQL_DATABASE: omn_production_db
      MYSQL_USER: omn_user
      MYSQL_PASSWORD: 2Lc5/aEa*X,2
      MYSQL_ROOT_PASSWORD: 2Lc5/aEa*X,2  
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
