name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: abhishek
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /var/www/html
          sudo git pull origin main
          sudo systemctl restart apache2
