name: Deploy WordPress Sites

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.EC2_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.EC2_SECRET_KEY }}
        aws-region: us-east-1

    - name: Run deployment commands on EC2 using SSM
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceids,Values=i-0316f10be4720a76c" \
          --parameters "commands=cd /var/www/site.openmynetwork.com && git pull origin main && cd /var/www/leepnetwork.com && git pull origin main && sudo systemctl restart apache2"
