name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/wordpress:latest

      - name: Deploy
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV }}" > .env

          docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress:latest
          docker-compose down
          docker-compose up -d
