name: Deploy WordPress to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grant permissions for wp-content
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/wp_omn_production/_work/site-omn-wp/site-omn-wp/wordpress/wp-content
          sudo chmod -R 755 /home/ubuntu/wp_omn_production/_work/site-omn-wp/site-omn-wp/wordpress/wp-content

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          cd ~/wp_omn_production/_work/site-omn-wp/site-omn-wp
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress-app .

  deploy:
    runs-on: self-hosted
    needs: build # Ensure this job runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fix directory permissions for wp-content
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/wp_omn_production/_work/site-omn-wp/site-omn-wp

      - name: Delete old content from wp-content
        run: |
          sudo rm -rf /home/ubuntu/wp_omn_production/_work/site-omn-wp/site-omn-wp/wordpress/wp-content/* || true

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/wordpress-app:latest

      - name: Pull Docker image to server
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress-app:latest

      - name: Build and deploy Docker containers
        run: |
          set -e # Exit on error
          cd ~/wp_omn_production/_work/site-omn-wp/site-omn-wp
          docker-compose down
          docker-compose up -d --build
