name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if necessary

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file for production
        run: |
          cd /home/ubuntu/omn_test_wp_server/_work/site-omn-wp/site-omn-wp
          touch .env
          echo "${{ secrets.PROD_ENV }}" > .env

      - name: Build Docker images
        run: docker-compose build | tee build.log

      - name: Push Docker images to Docker Hub
        run: docker-compose push

  deploy:
    runs-on: self-hosted
    needs: build 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          cd /home/ubuntu/omn_test_wp_server/_work/site-omn-wp/site-omn-wp
          touch .env
          echo "${{ secrets.PROD_ENV }}" > .env
          docker-compose pull
          docker-compose up -d
          docker-compose restart
